version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "ch.qos.logback:logback-classic"
        versions: [ "1.4.x" ]
