version: 2.1
orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.16

references:
  workspace_root: &workspace_root
                    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

workflows:
  version: 2.1
  build-test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
  release:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - test
          ssh-fingerprints: 'a5:27:08:2f:b8:1f:69:b6:31:4a:67:25:fd:5b:53:46'

  dryRunRelease:
    jobs:
      - circleci-maven-release-orb/run-maven-release:
          mvn-release-perform-command: >-
            mvn --batch-mode release:perform -DdryRun=true -s
            .circleci/.maven.xml
          ssh-fingerprints: 'a5:27:08:2f:b8:1f:69:b6:31:4a:67:25:fd:5b:53:46'

jobs:
  ##################################################################
  ##
  ##TEST JOB
  ##
  ##################################################################
  test:
    machine:
      image: ubuntu-2004:202107-02
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: mvn test -Dtest=org.testmonkeys.test.cucumber.spring.logback.TestRunner
      - run: mvn test -Dtest=org.testmonkeys.test.cucumber.spring.logback.TestOutput
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/repo/target
