version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn test -Dtest=org.testmonkeys.test.cucumber.spring.logback.TestRunner
      - run: mvn test -Dtest=org.testmonkeys.test.cucumber.spring.logback.TestOutput 


workflows:
  version: 2

  build-then-test:
    jobs:
      - test
